import Navbar from '@/components/Navbar';
import './globals.css';
import localFont from 'next/font/local';
import { Anton } from 'next/font/google';
import { ReactNode } from 'react';
import Modal from '@/components/ui/modal/modal';

const helveticaNowDisplay = localFont({
  variable: '--font-helveticaNowDisplay',
  src: [
    {
      weight: '100',
      style: 'normal',
      path: '/assets/fonts/HelveticaNowDisplay-Thin.woff2'
    },
    {
      weight: '300',
      style: 'normal',
      path: '/assets/fonts/HelveticaNowDisplay-Light.woff2'
    },
    {
      weight: '300',
      style: 'normal',
      path: '/assets/fonts/HelveticaNowDisplay-ExtLt.woff2'
    },
    {
      weight: '400',
      style: 'normal',
      path: '/assets/fonts/HelveticaNowDisplay-Regular.woff2'
    },
    {
      weight: '500',
      style: 'normal',
      path: '/assets/fonts/HelveticaNowDisplay-Medium.woff2'
    },
    {
      weight: '800',
      style: 'normal',
      path: '/assets/fonts/HelveticaNowDisplay-ExtraBold.woff2'
    },
    {
      weight: '900',
      style: 'normal',
      path: '/assets/fonts/HelveticaNowDisplay-Black.woff2'
    },
    {
      weight: 'bold',
      style: 'normal',
      path: '/assets/fonts/HelveticaNowDisplay-Bold.woff2'
    },
    {
      weight: 'normal',
      style: 'normal',
      path: '/assets/fonts/HelveticaNowDisplay-Regular.woff2'
    }
  ]
});

const anton = Anton({
  variable: '--anton-font',
  weight: '400',
  subsets: ['latin']
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html
      lang="en"
      className={`${helveticaNowDisplay.variable} ${anton.variable}`}
    >
      <body>
        <Navbar />
        <Modal />
        {children}
      </body>
    </html>
  );
}
